import type { FlagDefinition } from "./types";

/**
 * Common flags shared across all training scripts
 */
export const commonFlags: FlagDefinition[] = [
  {
    key: "seed",
    label: "Random Seed",
    type: "number",
    default: 42,
    description: "Global random seed for reproducibility",
    group: "General",
    appliesTo: ["pretrain", "sft", "grpo", "dpo", "tokenizer", "packing"],
  },
  {
    key: "output_dir",
    label: "Output Directory",
    type: "string",
    default: "/mnt/training/output",
    description: "Root output directory for checkpoints and logs",
    group: "General",
    appliesTo: ["pretrain", "sft", "grpo", "dpo", "tokenizer", "packing"],
  },
  {
    key: "log_interval",
    label: "Log Interval",
    type: "number",
    default: 10,
    description: "Log metrics every N steps",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "save_interval",
    label: "Save Interval",
    type: "number",
    default: 1000,
    description: "Save checkpoint every N steps",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "eval_interval",
    label: "Eval Interval",
    type: "number",
    default: 500,
    description: "Run evaluation every N steps",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "num_workers",
    label: "Dataloader Workers",
    type: "number",
    default: 4,
    description: "Number of dataloader worker processes",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo", "packing"],
  },
  {
    key: "resume_from_checkpoint",
    label: "Resume From Checkpoint",
    type: "string",
    description: "Path to checkpoint to resume training from",
    group: "General",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "compile",
    label: "Compile Model",
    type: "boolean",
    default: false,
    description: "Use torch.compile for faster training",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "wandb_project",
    label: "WandB Project",
    type: "string",
    description: "Weights & Biases project name (empty = disabled)",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "wandb_run_name",
    label: "WandB Run Name",
    type: "string",
    description: "Custom run name for W&B logging",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "hf_token",
    label: "HuggingFace Token",
    type: "string",
    description: "HuggingFace access token for gated models/datasets",
    group: "General",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
];

/**
 * Flags for the optimizer and learning rate schedule
 */
export const optimizerFlags: FlagDefinition[] = [
  {
    key: "learning_rate",
    label: "Learning Rate",
    type: "number",
    default: 3e-4,
    description: "Peak learning rate",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    validation: { min: 1e-8, max: 1.0 },
  },
  {
    key: "min_learning_rate",
    label: "Min Learning Rate",
    type: "number",
    default: 1e-5,
    description: "Minimum learning rate (for schedulers with decay)",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "weight_decay",
    label: "Weight Decay",
    type: "number",
    default: 0.1,
    description: "AdamW weight decay coefficient",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "adam_beta1",
    label: "Adam Beta1",
    type: "number",
    default: 0.9,
    description: "Adam beta1 parameter",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "adam_beta2",
    label: "Adam Beta2",
    type: "number",
    default: 0.95,
    description: "Adam beta2 parameter",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "adam_epsilon",
    label: "Adam Epsilon",
    type: "number",
    default: 1e-8,
    description: "Adam epsilon for numerical stability",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "max_grad_norm",
    label: "Max Gradient Norm",
    type: "number",
    default: 1.0,
    description: "Maximum gradient norm for clipping",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "lr_scheduler",
    label: "LR Scheduler",
    type: "select",
    default: "cosine",
    options: [
      { label: "Cosine", value: "cosine" },
      { label: "Linear", value: "linear" },
      { label: "Warmup Stable Decay", value: "warmup_stable_decay" },
      { label: "Constant", value: "constant" },
    ],
    description: "Learning rate scheduler type",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "warmup_steps",
    label: "Warmup Steps",
    type: "number",
    default: 100,
    description: "Number of LR warmup steps",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "optimizer",
    label: "Optimizer",
    type: "select",
    default: "adamw",
    options: [
      { label: "AdamW", value: "adamw" },
      { label: "Adam", value: "adam" },
      { label: "SGD", value: "sgd" },
      { label: "LAMB", value: "lamb" },
    ],
    description: "Optimizer type",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
];
