import type { FlagDefinition, FlagGroup } from "./types";

/**
 * Hivemind-specific flags for decentralized training
 */
export const hivemindFlags: FlagDefinition[] = [
  {
    key: "bootstrap_peer",
    label: "Bootstrap Peer Multi-Address",
    type: "string",
    default: "/ip4/0.0.0.0/tcp/31337/p2p/...",
    description: "Multi-address of the bootstrap peer for DHT discovery",
    group: "P2P Network",
    required: true,
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "host_maddrs",
    label: "Host Multi-Address",
    type: "string",
    default: "/ip4/0.0.0.0/tcp/31337",
    description: "Local multi-address to listen on for incoming peer connections",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "announce_maddrs",
    label: "Announce Multi-Address",
    type: "string",
    description: "Public multi-address to announce to other peers (if behind NAT)",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "identity_path",
    label: "Peer Identity Path",
    type: "string",
    default: "./hivemind_peer.key",
    description: "Path to save/load peer identity (for persistent peer IDs)",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "dht_port",
    label: "DHT Port",
    type: "number",
    default: 31337,
    description: "Port for DHT (Distributed Hash Table) peer discovery",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "allreduce_port",
    label: "AllReduce Port",
    type: "number",
    default: 31338,
    description: "Port for decentralized gradient all-reduce (averaging)",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "compression",
    label: "Gradient Compression",
    type: "select",
    default: "float16",
    options: [
      { label: "None", value: "none" },
      { label: "FP16", value: "float16" },
      { label: "8-bit Quantile", value: "quantile_8bit" },
      { label: "8-bit MinMax", value: "min_max_8bit" },
      { label: "8-bit Uniform", value: "uniform_8bit" },
    ],
    description: "Gradient compression type to reduce communication bandwidth",
    group: "Compression",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "max_peers",
    label: "Max Peers",
    type: "number",
    default: 32,
    description: "Maximum number of connected peers in the training swarm",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "min_peers",
    label: "Min Peers",
    type: "number",
    default: 1,
    description: "Minimum number of peers before training begins",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "target_batch_size",
    label: "Target Batch Size",
    type: "number",
    default: 2048,
    description: "Target total batch size across all peers (peers adjust throughput to match)",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "gradient_averaging_timeout",
    label: "AllReduce Timeout",
    type: "number",
    default: 30,
    description: "Timeout in seconds for gradient averaging rounds",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "matchmaking_time",
    label: "Matchmaking Time",
    type: "number",
    default: 5,
    description: "Time in seconds to wait for peers before averaging gradients",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "averaging_alpha",
    label: "Averaging Alpha",
    type: "number",
    default: 0.5,
    description: "Exponential moving average coefficient for peer parameter averaging (0 = reset, 1 = full average)",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "delay_optimizer_step",
    label: "Delay Optimizer Step",
    type: "boolean",
    default: true,
    description: "Delay local optimizer step until after gradient averaging",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "client_mode",
    label: "Client Mode",
    type: "boolean",
    default: false,
    description: "Run in client mode (contribute gradients but don't host DHT data)",
    group: "P2P Network",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
  {
    key: "verbose",
    label: "Verbose Logging",
    type: "boolean",
    default: false,
    description: "Enable verbose Hivemind logging including DHT and connection details",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    backend: "hivemind",
  },
];

export const hivemindSchema = {
  groups: [
    { label: "P2P Network", flags: hivemindFlags.filter(f => f.group === "P2P Network") },
    { label: "Training", flags: hivemindFlags.filter(f => f.group === "Training") },
    { label: "Compression", flags: hivemindFlags.filter(f => f.group === "Compression") },
    { label: "Logging", flags: hivemindFlags.filter(f => f.group === "Logging") },
  ],
};
