import type { FlagDefinition } from "./types";
import { commonFlags, optimizerFlags } from "./common";

/**
 * SFT (Supervised Fine-Tuning) specific flags
 */
const sftSpecific: FlagDefinition[] = [
  {
    key: "model_name_or_path",
    label: "Model Path",
    type: "string",
    description: "Path to pretrained model checkpoint or HuggingFace model ID",
    group: "Model",
    required: true,
    appliesTo: ["sft"],
  },
  {
    key: "data_path",
    label: "Data Path",
    type: "string",
    default: "/mnt/training/data/sft",
    description: "Path to SFT dataset (JSONL with instruction/response pairs)",
    group: "Data",
    required: true,
    appliesTo: ["sft"],
  },
  {
    key: "batch_size",
    label: "Per-Device Batch Size",
    type: "number",
    default: 4,
    description: "Micro-batch size per GPU device",
    group: "Training",
    required: true,
    appliesTo: ["sft"],
  },
  {
    key: "gradient_accumulation",
    label: "Gradient Accumulation",
    type: "number",
    default: 4,
    description: "Accumulate gradients over N steps",
    group: "Training",
    appliesTo: ["sft"],
  },
  {
    key: "num_epochs",
    label: "Number of Epochs",
    type: "number",
    default: 3,
    description: "Number of fine-tuning epochs",
    group: "Training",
    appliesTo: ["sft"],
  },
  {
    key: "max_len",
    label: "Max Sequence Length",
    type: "number",
    default: 4096,
    description: "Maximum sequence length for SFT examples",
    group: "Data",
    appliesTo: ["sft"],
  },
  {
    key: "packing",
    label: "Sequence Packing",
    type: "boolean",
    default: true,
    description: "Pack multiple short sequences into one for efficiency",
    group: "Data",
    appliesTo: ["sft"],
  },
  {
    key: "learning_rate",
    label: "Learning Rate",
    type: "number",
    default: 1e-5,
    description: "Peak learning rate (typically lower than pretrain)",
    group: "Optimizer",
    appliesTo: ["sft"],
  },
  {
    key: "use_lora",
    label: "Use LoRA",
    type: "boolean",
    default: false,
    description: "Enable LoRA (Low-Rank Adaptation) for parameter-efficient fine-tuning",
    group: "LoRA",
    appliesTo: ["sft"],
  },
  {
    key: "lora_r",
    label: "LoRA Rank",
    type: "number",
    default: 16,
    description: "LoRA rank (r) parameter",
    group: "LoRA",
    appliesTo: ["sft"],
  },
  {
    key: "lora_alpha",
    label: "LoRA Alpha",
    type: "number",
    default: 32,
    description: "LoRA scaling parameter (alpha)",
    group: "LoRA",
    appliesTo: ["sft"],
  },
  {
    key: "lora_dropout",
    label: "LoRA Dropout",
    type: "number",
    default: 0.05,
    description: "LoRA dropout probability",
    group: "LoRA",
    appliesTo: ["sft"],
  },
  {
    key: "lora_target_modules",
    label: "LoRA Target Modules",
    type: "multiselect",
    default: ["q_proj", "v_proj"],
    options: [
      { label: "Q Projection", value: "q_proj" },
      { label: "K Projection", value: "k_proj" },
      { label: "V Projection", value: "v_proj" },
      { label: "O Projection", value: "o_proj" },
      { label: "Gate (FFN)", value: "gate_proj" },
      { label: "Up (FFN)", value: "up_proj" },
      { label: "Down (FFN)", value: "down_proj" },
    ],
    description: "Which modules to apply LoRA to",
    group: "LoRA",
    appliesTo: ["sft"],
  },
  {
    key: "val_split",
    label: "Validation Split",
    type: "number",
    default: 0.01,
    description: "Fraction of data for validation",
    group: "Data",
    appliesTo: ["sft"],
  },
];

export const sftSchema = {
  script: "train_sft.py",
  description: "Supervised fine-tuning of pretrained models on instruction-response pairs.",
  groups: [
    { label: "Model", flags: sftSpecific.filter(f => f.group === "Model") },
    { label: "Data", flags: sftSpecific.filter(f => f.group === "Data") },
    { label: "Training", flags: sftSpecific.filter(f => f.group === "Training") },
    { label: "Optimizer", flags: optimizerFlags.filter(f => f.appliesTo.includes("sft")) },
    { label: "LoRA", flags: sftSpecific.filter(f => f.group === "LoRA") },
    { label: "Logging", flags: commonFlags.filter(f => f.group === "Logging" && f.appliesTo.includes("sft")) },
    { label: "General", flags: commonFlags.filter(f => f.group === "General" && f.appliesTo.includes("sft")) },
  ],
};
