import type { FlagDefinition } from "./types";

/**
 * Architecture variant flags
 * These control the model architecture: dense, jamba, parallel layers, MLA, Mamba, MoD, MTP
 */
export const architectureFlags: FlagDefinition[] = [
  {
    key: "model_type",
    label: "Architecture",
    type: "select",
    default: "dense",
    options: [
      { label: "Dense Transformer", value: "dense" },
      { label: "Jamba (Hybrid)", value: "jamba" },
      { label: "Parallel Layers", value: "parallel" },
      { label: "Multi-Head Latent Attention", value: "mla" },
      { label: "Mamba SSM", value: "mamba" },
      { label: "Mixture of Depth", value: "mod" },
      { label: "Multi-Token Prediction", value: "mtp" },
    ],
    description: "Model architecture variant",
    group: "Architecture",
    required: true,
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "vocab_size",
    label: "Vocab Size",
    type: "number",
    default: 100352,
    description: "Vocabulary size (tokenizer-dependent, default for Qwen/GPT tokenizers)",
    group: "Architecture",
    required: true,
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    validation: { min: 1000, max: 1000000 },
  },
  {
    key: "hidden_dim",
    label: "Hidden Dimension",
    type: "number",
    default: 768,
    description: "Transformer hidden dimension (d_model)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "intermediate_dim",
    label: "FFN Intermediate Dim",
    type: "number",
    description: "Feed-forward network intermediate dimension. Auto-calculated if not set",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "num_layers",
    label: "Number of Layers",
    type: "number",
    default: 12,
    description: "Number of transformer layers",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    validation: { min: 1, max: 1000 },
  },
  {
    key: "num_heads",
    label: "Attention Heads",
    type: "number",
    default: 12,
    description: "Number of attention heads",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    validation: { min: 1, max: 1024 },
  },
  {
    key: "num_kv_heads",
    label: "KV Heads",
    type: "number",
    default: 4,
    description: "Number of key-value heads for GQA/MQA. Defaults to num_heads if not set",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "max_seq_len",
    label: "Max Sequence Length",
    type: "number",
    default: 4096,
    description: "Maximum sequence length for positional encoding and RoPE",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "rope_theta",
    label: "RoPE Theta",
    type: "number",
    default: 10000,
    description: "Rotary Position Embedding theta/base frequency",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "dropout",
    label: "Dropout",
    type: "number",
    default: 0.0,
    description: "Dropout probability (usually 0 for pretrain, >0 for fine-tuning)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
    validation: { min: 0, max: 0.99 },
  },
  {
    key: "attn_dropout",
    label: "Attention Dropout",
    type: "number",
    default: 0.0,
    description: "Dropout applied to attention weights",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "norm_type",
    label: "Normalization Type",
    type: "select",
    default: "rmsnorm",
    options: [
      { label: "RMSNorm", value: "rmsnorm" },
      { label: "LayerNorm", value: "layernorm" },
    ],
    description: "Type of normalization to use in transformer blocks",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "activation_type",
    label: "Activation Function",
    type: "select",
    default: "silu",
    options: [
      { label: "SiLU / Swish", value: "silu" },
      { label: "GELU", value: "gelu" },
      { label: "ReLU", value: "relu" },
    ],
    description: "Activation function for FFN layers",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "head_dim",
    label: "Head Dimension",
    type: "number",
    default: 128,
    description: "Dimension per attention head (MLA uses qk_nope_dim + qk_rope_dim)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "num_experts",
    label: "Number of Experts",
    type: "number",
    default: 8,
    description: "Number of experts in MoE/MoD layers (only for jamba/mod)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "top_k_experts",
    label: "Top-K Experts",
    type: "number",
    default: 2,
    description: "Number of active experts per token (only for jamba/mod)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "num_experts_per_freq",
    label: "Experts Per Frequency",
    type: "number",
    default: 2,
    description: "MoE layer frequency — every N layers becomes MoE (jamba)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "jamba_attn_layers",
    label: "Jamba Attention Layers",
    type: "number",
    default: 8,
    description: "Number of attention layers in Jamba hybrid (rest are Mamba)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "mamba_expand",
    label: "Mamba Expand Factor",
    type: "number",
    default: 2,
    description: "Mamba state expansion factor (for mamba/jamba)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "mamba_d_state",
    label: "Mamba State Dim",
    type: "number",
    default: 16,
    description: "Mamba SSM state dimension",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "parallel_attn_ffn",
    label: "Parallel Attn+FFN",
    type: "boolean",
    default: false,
    description: "Run attention and FFN in parallel (parallel layers variant)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "mtp_depth",
    label: "MTP Depth",
    type: "number",
    default: 1,
    description: "Number of future tokens to predict (Multi-Token Prediction)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "use_sliding_window",
    label: "Sliding Window Attention",
    type: "boolean",
    default: false,
    description: "Enable sliding window attention",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "sliding_window_size",
    label: "Sliding Window Size",
    type: "number",
    default: 4096,
    description: "Sliding window size for attention",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "num_shared_experts",
    label: "Shared Experts",
    type: "number",
    default: 2,
    description: "Number of shared experts (DeepSeek-style, always active)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "qk_rope_head_dim",
    label: "QK RoPE Head Dim",
    type: "number",
    default: 64,
    description: "Head dimension for RoPE in Q/K (MLA-specific)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "qk_nope_head_dim",
    label: "QK NoPE Head Dim",
    type: "number",
    default: 128,
    description: "Head dimension for NoPE in Q/K (MLA-specific)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "v_head_dim",
    label: "V Head Dim",
    type: "number",
    default: 128,
    description: "Head dimension for V (MLA-specific)",
    group: "Architecture",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
];
