import type { FlagDefinition, FlagGroup } from "./types";

/**
 * DeepSpeed-specific flags for ZeRO optimization
 */
export const deepspeedFlags: FlagDefinition[] = [
  {
    key: "zero_stage",
    label: "ZeRO Stage",
    type: "select",
    default: "2",
    options: [
      { label: "ZeRO-0 (Disabled)", value: "0" },
      { label: "ZeRO-1 (Optimizer)", value: "1" },
      { label: "ZeRO-2 (Gradient)", value: "2" },
      { label: "ZeRO-3 (Parameter)", value: "3" },
    ],
    description: "ZeRO optimization stage — higher stages reduce memory but increase communication",
    group: "ZeRO",
    required: true,
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "offload_optimizer",
    label: "Offload Optimizer",
    type: "boolean",
    default: false,
    description: "Offload optimizer states to CPU (reduces GPU memory at cost of speed)",
    group: "ZeRO",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "offload_param",
    label: "Offload Parameters",
    type: "boolean",
    default: false,
    description: "Offload parameters to CPU (ZeRO-3 only)",
    group: "ZeRO",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "offload_device",
    label: "Offload Device",
    type: "select",
    default: "cpu",
    options: [
      { label: "CPU", value: "cpu" },
      { label: "NVMe", value: "nvme" },
    ],
    description: "Device to offload optimizer/parameter states to",
    group: "ZeRO",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "zero_optimization_stage3_param_persistence_threshold",
    label: "Param Persistence Threshold",
    type: "number",
    default: 0,
    description: "ZeRO-3 threshold — parameters above this size are not offloaded during forward/backward",
    group: "ZeRO",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "zero_optimization_stage3_max_reuse_distance",
    label: "Max Reuse Distance",
    type: "number",
    default: 0,
    description: "ZeRO-3 — maximum reuse distance before parameter offload",
    group: "ZeRO",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "overlap_comm",
    label: "Overlap Communication",
    type: "boolean",
    default: true,
    description: "Overlap gradient all-reduce with backward pass computation",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "allgather_partitions",
    label: "AllGather Partitions",
    type: "boolean",
    default: true,
    description: "Use partitioned all-gather for gradient averaging",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "reduce_scatter",
    label: "Reduce Scatter",
    type: "boolean",
    default: true,
    description: "Use reduce-scatter for gradient reduction instead of all-reduce",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "contiguous_gradients",
    label: "Contiguous Gradients",
    type: "boolean",
    default: true,
    description: "Use contiguous gradient buffers for efficiency",
    group: "Performance",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "steps_per_print",
    label: "Steps Per Print",
    type: "number",
    default: 10,
    description: "Log DeepSpeed progress every N steps",
    group: "Logging",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "train_batch_size",
    label: "Global Train Batch Size",
    type: "number",
    description: "Effective training batch size across all devices (if set, overrides per-device config)",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "train_micro_batch_size",
    label: "Micro Batch Size",
    type: "number",
    description: "Per-device micro batch size (overrides per-device batch_size if set)",
    group: "Training",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "fp16",
    label: "FP16 Mixed Precision",
    type: "boolean",
    default: true,
    description: "Enable FP16 training with dynamic loss scaling",
    group: "Precision",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "bf16",
    label: "BF16 Mixed Precision",
    type: "boolean",
    default: false,
    description: "Enable BF16 training (preferred over FP16 on Ampere+ GPUs)",
    group: "Precision",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
  {
    key: "gradient_clipping",
    label: "Gradient Clipping Value",
    type: "number",
    default: 1.0,
    description: "Max gradient norm for clipping (0 = disabled)",
    group: "Optimizer",
    appliesTo: ["pretrain", "sft", "grpo", "dpo"],
  },
];

export const deepspeedSchema = {
  groups: [
    { label: "ZeRO Optimization", flags: deepspeedFlags.filter(f => f.group === "ZeRO") },
    { label: "Performance", flags: deepspeedFlags.filter(f => f.group === "Performance") },
    { label: "Precision", flags: deepspeedFlags.filter(f => f.group === "Precision") },
    { label: "Training", flags: deepspeedFlags.filter(f => f.group === "Training") },
    { label: "Optimizer", flags: deepspeedFlags.filter(f => f.group === "Optimizer") },
    { label: "Logging", flags: deepspeedFlags.filter(f => f.group === "Logging") },
  ],
};
