import type { FlagDefinition } from "./types";
import { commonFlags, optimizerFlags } from "./common";

/**
 * DPO (Direct Preference Optimization) specific flags
 */
const dpoSpecific: FlagDefinition[] = [
  {
    key: "model_name_or_path",
    label: "Model Path",
    type: "string",
    description: "Path to SFT model checkpoint or HuggingFace model ID",
    group: "Model",
    required: true,
    appliesTo: ["dpo"],
  },
  {
    key: "data_path",
    label: "Data Path",
    type: "string",
    default: "/mnt/training/data/dpo",
    description: "Path to DPO dataset (JSONL with chosen/rejected pairs)",
    group: "Data",
    required: true,
    appliesTo: ["dpo"],
  },
  {
    key: "ref_model",
    label: "Reference Model",
    type: "string",
    description: "Path to reference model (frozen, for KL regularization)",
    group: "Model",
    appliesTo: ["dpo"],
  },
  {
    key: "batch_size",
    label: "Per-Device Batch Size",
    type: "number",
    default: 4,
    description: "Micro-batch size per GPU device",
    group: "Training",
    required: true,
    appliesTo: ["dpo"],
  },
  {
    key: "gradient_accumulation",
    label: "Gradient Accumulation",
    type: "number",
    default: 4,
    description: "Accumulate gradients over N steps",
    group: "Training",
    appliesTo: ["dpo"],
  },
  {
    key: "num_epochs",
    label: "Number of Epochs",
    type: "number",
    default: 3,
    description: "Number of DPO training epochs",
    group: "Training",
    appliesTo: ["dpo"],
  },
  {
    key: "beta",
    label: "Beta (KL Regularization)",
    type: "number",
    default: 0.1,
    description: "Beta parameter controlling deviation from reference model (higher = more constrained)",
    group: "DPO",
    appliesTo: ["dpo"],
  },
  {
    key: "loss_type",
    label: "Loss Type",
    type: "select",
    default: "sigmoid",
    options: [
      { label: "Sigmoid (Standard DPO)", value: "sigmoid" },
      { label: "IPO", value: "ipo" },
      { label: "KTO", value: "kto" },
      { label: "CPO", value: "cpo" },
      { label: "SimPO", value: "simpo" },
    ],
    description: "DPO loss variant",
    group: "DPO",
    appliesTo: ["dpo"],
  },
  {
    key: "label_smoothing",
    label: "Label Smoothing",
    type: "number",
    default: 0.0,
    description: "Label smoothing for DPO loss (0 = off)",
    group: "DPO",
    appliesTo: ["dpo"],
  },
  {
    key: "max_len",
    label: "Max Sequence Length",
    type: "number",
    default: 2048,
    description: "Maximum sequence length for DPO pairs",
    group: "Data",
    appliesTo: ["dpo"],
  },
  {
    key: "learning_rate",
    label: "Learning Rate",
    type: "number",
    default: 5e-6,
    description: "Peak learning rate (typically very small for DPO)",
    group: "Optimizer",
    appliesTo: ["dpo"],
  },
  {
    key: "use_lora",
    label: "Use LoRA",
    type: "boolean",
    default: true,
    description: "Enable LoRA for parameter-efficient DPO training",
    group: "LoRA",
    appliesTo: ["dpo"],
  },
  {
    key: "lora_r",
    label: "LoRA Rank",
    type: "number",
    default: 16,
    description: "LoRA rank (r) parameter",
    group: "LoRA",
    appliesTo: ["dpo"],
  },
  {
    key: "lora_alpha",
    label: "LoRA Alpha",
    type: "number",
    default: 32,
    description: "LoRA scaling parameter (alpha)",
    group: "LoRA",
    appliesTo: ["dpo"],
  },
  {
    key: "lora_dropout",
    label: "LoRA Dropout",
    type: "number",
    default: 0.05,
    description: "LoRA dropout probability",
    group: "LoRA",
    appliesTo: ["dpo"],
  },
];

export const dpoSchema = {
  script: "train_dpo.py",
  description: "Direct Preference Optimization — align models with human preferences using pairwise preference data.",
  groups: [
    { label: "Model", flags: dpoSpecific.filter(f => f.group === "Model") },
    { label: "Data", flags: dpoSpecific.filter(f => f.group === "Data") },
    { label: "Training", flags: dpoSpecific.filter(f => f.group === "Training") },
    { label: "DPO Settings", flags: dpoSpecific.filter(f => f.group === "DPO") },
    { label: "Optimizer", flags: optimizerFlags.filter(f => f.appliesTo.includes("dpo")) },
    { label: "LoRA", flags: dpoSpecific.filter(f => f.group === "LoRA") },
    { label: "Logging", flags: commonFlags.filter(f => f.group === "Logging" && f.appliesTo.includes("dpo")) },
    { label: "General", flags: commonFlags.filter(f => f.group === "General" && f.appliesTo.includes("dpo")) },
  ],
};
