import type { FlagDefinition } from "./types";
import { commonFlags, optimizerFlags } from "./common";

/**
 * GRPO (Group Relative Policy Optimization) specific flags
 */
const grpoSpecific: FlagDefinition[] = [
  {
    key: "model_name_or_path",
    label: "Model Path",
    type: "string",
    description: "Path to SFT model checkpoint or HuggingFace model ID",
    group: "Model",
    required: true,
    appliesTo: ["grpo"],
  },
  {
    key: "data_path",
    label: "Data Path",
    type: "string",
    default: "/mnt/training/data/grpo",
    description: "Path to GRPO dataset (prompts for RL training)",
    group: "Data",
    required: true,
    appliesTo: ["grpo"],
  },
  {
    key: "ref_model",
    label: "Reference Model",
    type: "string",
    description: "Path to reference model for KL penalty (defaults to model_name_or_path)",
    group: "Model",
    appliesTo: ["grpo"],
  },
  {
    key: "reward_model",
    label: "Reward Model",
    type: "string",
    description: "Path to reward model for scoring completions",
    group: "Model",
    appliesTo: ["grpo"],
  },
  {
    key: "batch_size",
    label: "Per-Device Batch Size",
    type: "number",
    default: 8,
    description: "Micro-batch size per GPU device",
    group: "Training",
    required: true,
    appliesTo: ["grpo"],
  },
  {
    key: "gradient_accumulation",
    label: "Gradient Accumulation",
    type: "number",
    default: 4,
    description: "Accumulate gradients over N steps",
    group: "Training",
    appliesTo: ["grpo"],
  },
  {
    key: "num_epochs",
    label: "Number of Epochs",
    type: "number",
    default: 1,
    description: "Number of RL training epochs",
    group: "Training",
    appliesTo: ["grpo"],
  },
  {
    key: "group_size",
    label: "Group Size",
    type: "number",
    default: 8,
    description: "Number of completions sampled per prompt in each group",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "top_k",
    label: "Top-K Sampling",
    type: "number",
    default: 50,
    description: "Top-K for response sampling",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "top_p",
    label: "Top-P Sampling",
    type: "number",
    default: 0.9,
    description: "Nucleus sampling threshold",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "temperature",
    label: "Temperature",
    type: "number",
    default: 0.7,
    description: "Sampling temperature for response generation",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "max_new_tokens",
    label: "Max Generated Tokens",
    type: "number",
    default: 1024,
    description: "Maximum tokens per generated response",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "kl_coef",
    label: "KL Coefficient",
    type: "number",
    default: 0.04,
    description: "KL penalty coefficient (higher = more conservative)",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "clip_eps",
    label: "Clip Epsilon",
    type: "number",
    default: 0.2,
    description: "PPO clipping epsilon for GRPO",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "reward_scale",
    label: "Reward Scale",
    type: "number",
    default: 1.0,
    description: "Scaling factor applied to rewards",
    group: "GRPO",
    appliesTo: ["grpo"],
  },
  {
    key: "learning_rate",
    label: "Learning Rate",
    type: "number",
    default: 5e-6,
    description: "Peak learning rate (typically very small for RL)",
    group: "Optimizer",
    appliesTo: ["grpo"],
  },
  {
    key: "use_vllm",
    label: "Use vLLM for Generation",
    type: "boolean",
    default: false,
    description: "Use vLLM as a fast inference engine for response generation",
    group: "Performance",
    appliesTo: ["grpo"],
  },
];

export const grpoSchema = {
  script: "train_grpo.py",
  description: "Group Relative Policy Optimization — RL fine-tuning using grouped reward comparisons.",
  groups: [
    { label: "Model", flags: grpoSpecific.filter(f => f.group === "Model") },
    { label: "Data", flags: grpoSpecific.filter(f => f.group === "Data") },
    { label: "Training", flags: grpoSpecific.filter(f => f.group === "Training") },
    { label: "GRPO Settings", flags: grpoSpecific.filter(f => f.group === "GRPO") },
    { label: "Optimizer", flags: optimizerFlags.filter(f => f.appliesTo.includes("grpo")) },
    { label: "Performance", flags: grpoSpecific.filter(f => f.group === "Performance") },
    { label: "Logging", flags: commonFlags.filter(f => f.group === "Logging" && f.appliesTo.includes("grpo")) },
    { label: "General", flags: commonFlags.filter(f => f.group === "General" && f.appliesTo.includes("grpo")) },
  ],
};
